### PR TITLE
Add nightly to travis testing matrix and remove unsupported

### PR DESCRIPTION
**Pull request by andypost**
7.0 and 7.1 is unsupported https://www.php.net/supported-versions.php

### CODE REVIEW

**Comment by andypost** [comment]
There's one failed test for 8.x 
```
FAILED TEST SUMMARY
---------------------------------------------------------------------
XHProf: Test Curl Additional Info
Author: longxinhui [tests/xhprof_012.phpt]
```

**Comment by andypost** [comment]
Copied the test looks for php 8 curl integration needs change
```diff
 main()                                  : ct=       1; wt=*;
 main()==>curl_close                     : ct=       1; wt=*;
-main()==>curl_exec#https://www.php.net/ : ct=       1; wt=*;
-main()==>curl_getinfo                   : ct=       1; wt=*;
+main()==>curl_exec                      : ct=       1; wt=*;
 main()==>curl_init                      : ct=       1; wt=*;
 main()==>curl_setopt                    : ct=       2; wt=*;
 main()==>xhprof_disable                 : ct=       1; wt=*;
```

**Comment by andypost** [comment]
Fixes for

- https://github.com/php/php-src/blob/master/UPGRADING.INTERNALS#L141
> s. The zend_fcall_info no_separation flag has been removed, and separation is
      never allowed. If you wish to pass (or allow passing) arguments by
      reference, explicitly create those arguments as references using
      ZEND_MAKE_REF. This removal also affects call_user_function_ex(), which
      should be replaced by call_user_function().

- https://github.com/php/php-src/blob/master/Zend/zend_compile.h#L735
> extern ZEND_API zend_op_array *(*zend_compile_string)(zval *source_string, const char *filename);

**Comment by andypost** [comment]
Curl changed return type to return object instead of resource, that's why test failed

https://github.com/php/php-src/blob/master/UPGRADING#L948

**Comment by andypost** [comment]
The related change is https://github.com/php/php-src/pull/5402

**Comment by longxinH** [comment]
@andypost Thank you, is there any other solution I try

**Comment by andypost** [comment]
I used to run the test to try get object but stuck at this line https://github.com/longxinH/xhprof/blob/master/extension/xhprof.c#L1519-L1520
```
make NO_INTERACTION=1 REPORT_EXIT_STATUS=1 test \
    PHP_TEST_SHARED_EXTENSIONS="-d extension=/usr/lib/php8/modules/curl.so -d extension=modules/xhprof.so" \
    TESTS=tests/xhprof_012_8.phpt
```

**Comment by andypost** [comment]
It just type 8 (object) in 8+ so after https://github.com/longxinH/xhprof/pull/44 makes sense to create new release)

**Pull request merged**
