### PR TITLE
Set SVG render as default for callgraph.php

### PR DESCRIPTION
**Pull request by andypost**
This is render needs no server fonts and doing processing faster nowadays

### CODE REVIEW

**Comment by longxinH** [comment]
@andypost Great

**Comment by longxinH** [comment]
https://github.com/longxinH/xhprof/releases/tag/v2.3.1

**Comment by andypost** [comment]
Thank you! please publish PECL release

**Comment by longxinH** [comment]
Done. https://pecl.php.net/package/xhprof/2.3.1

**Comment by andypost** [comment]
Thank you 😊

**Pull request merged**
